# =====================================================
# CONFIGURATION EXTERNALISÉE - MICROSERVICE RULENAME
# =====================================================

# Identité et Port d'écoute
spring.application.name=rulename
server.port=8084

# Base de Données H2 (In-Memory)
spring.datasource.url=jdbc:h2:mem:rulenamedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuration JPA & Initialisation SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Découverte de Services (HashiCorp Consul)
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true

# Surveillance de Santé (Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
