# ===================================================
# CONFIGURATION EXTERNALISÉE - MICROSERVICE USER
# ===================================================

# Identité et Port d'écoute
spring.application.name=user
server.port=8086

# Base de Données MySQL 8.0 (Persistant)
spring.datasource.url=jdbc:mysql://poseidon-db:3306/poseidon_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Découverte de Services (HashiCorp Consul)
spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.prefer-ip-address=true

# Surveillance de Santé (Actuator)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
